version: '3.3'

volumes:
  media:
  pg_data:
  static:

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    env_file: .env
    container_name: foodgram_backend
    build: /foodgram_backend
    volumes:
      - media:/app/media/
      - static:/backend_static/
    depends_on:
      - db
    
  frontend:
    container_name: foodgram-front
    build: /frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  nginx:
    container_name: foodgram-proxy
    build: ./infra/
    ports:
      - "80:80"
    volumes:
      - media:/var/www/media/
      - static:/staticfiles/
    depends_on:
      - backend
      - frontend
      - db
