# Generated by Django 5.2.5 on 2025-08-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='short_url',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
