# Generated by Django 5.2.5 on 2025-09-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredients_options_alter_recipes_short_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='short_url',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг для прямой ссылки'),
        ),
    ]
