# Generated by Django 5.2.5 on 2025-08-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'ordering': ['recipe_id'], 'verbose_name': 'Ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingredient',
            new_name='ingredient_id',
        ),
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='recipe',
            new_name='recipe_id',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredients', through_fields=('recipe_id', 'ingredient_id'), to='recipes.ingredients', verbose_name='Ингредиенты'),
        ),
    ]
