# Generated by Django 5.2.5 on 2025-08-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipes_options_rename_tag_recipes_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='quantity',
            new_name='amount',
        ),
    ]
