# Generated by Django 5.2.5 on 2025-09-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_follow_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='non_self_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id__ne', models.F('following_id'))), fields=('user', 'following'), name='non_self_follow'),
        ),
    ]
